# Generated by Django 5.2.6 on 2026-03-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_inicial_ia', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
                ('total_mensagens', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocao_relacionada', models.CharField(max_length=50)),
                ('texto_pergunta', models.TextField()),
                ('ordem', models.IntegerField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.TextField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.diario')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoEmocional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocao_selecionada', models.CharField(db_index=True, max_length=50)),
                ('data_inicio', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status_sessao', models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('expirada', 'Expirada')], default='ativa', max_length=20)),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='diario',
            name='sessao_emocional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diario.sessaoemocional'),
        ),
    ]
