# Generated by Django 6.0.2 on 2026-02-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_aluno_data_nascimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_inicial_ia', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocao_relacionada', models.CharField(max_length=50)),
                ('texto_pergunta', models.TextField()),
                ('ordem', models.IntegerField()),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.TextField()),
                ('data_resposta', models.DateTimeField(auto_now_add=True)),
                ('sentimento_detectado', models.CharField(blank=True, max_length=50, null=True)),
                ('score_sentimento', models.FloatField(blank=True, null=True)),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.diario')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoEmocional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocao_selecionada', models.CharField(max_length=50)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('status_sessao', models.CharField(max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.aluno')),
            ],
        ),
        migrations.AddField(
            model_name='diario',
            name='sessao_emocional',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diario.sessaoemocional'),
        ),
    ]
