# Generated by Django 6.0.2 on 2026-02-16 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_aluno_data_nascimento_and_more'),
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoemocional',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.aluno'),
        ),
    ]
