# Generated by Django 6.0.2 on 2026-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_alter_sessaoemocional_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='score_sentimento',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='sentimento_detectado',
        ),
        migrations.AlterField(
            model_name='diario',
            name='mensagem_inicial_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
