# Generated by Django 5.2.6 on 2026-04-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_alter_diario_id_alter_pergunta_id_alter_resposta_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaoemocional',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='sessaoemocional',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='sessaoemocional',
            name='status_sessao',
        ),
        migrations.AlterField(
            model_name='sessaoemocional',
            name='emocao_selecionada',
            field=models.CharField(choices=[('feliz', 'Feliz'), ('triste', 'Triste'), ('muito_triste', 'Muito Triste'), ('raiva', 'Raiva'), ('neutro', 'Neutro')], db_index=True, max_length=50),
        ),
    ]
