# Generated by Django 5.2.6 on 2026-03-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_remove_resposta_score_sentimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diario',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessaoemocional',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sessaoemocional',
            name='status_sessao',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('encerrada', 'Encerrada'), ('expirada', 'Expirada')], default='ativa', max_length=20),
        ),
    ]
