# Generated by Django 5.2.6 on 2026-03-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_alter_diario_id_alter_pergunta_id_alter_resposta_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diario',
            name='total_mensagens',
            field=models.IntegerField(default=0),
        ),
    ]
