# Generated by Django 5.2.6 on 2026-03-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_diario_total_mensagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessaoemocional',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='sessaoemocional',
            name='emocao_selecionada',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
