# Generated by Django 5.2.6 on 2026-03-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseResposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentimento_detectado', models.CharField(blank=True, max_length=50, null=True)),
                ('score_sentimento', models.FloatField(blank=True, null=True)),
                ('modelo_ia', models.CharField(blank=True, max_length=100, null=True)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('resposta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diario.resposta')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseSessao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emocao_predominante', models.CharField(blank=True, max_length=50, null=True)),
                ('score_medio', models.FloatField(blank=True, null=True)),
                ('variacao_emocional', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes_ia', models.TextField(blank=True, null=True)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('sessao_emocional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diario.sessaoemocional')),
            ],
        ),
    ]
