# Generated by Django 6.0.2 on 2026-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analiseresposta',
            name='confianca',
        ),
        migrations.AlterField(
            model_name='analiseresposta',
            name='modelo_ia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
