# Generated by Django 5.2.6 on 2026-03-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analise', '0002_remove_analiseresposta_confianca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analiseresposta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='analisesessao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
