# Generated by Django 6.0.2 on 2026-02-04 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(max_length=30)),
                ('data_criacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.usuario')),
                ('data_nascimento', models.DateTimeField()),
                ('tipo_deficiencia', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Educador',
            fields=[
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.usuario')),
                ('area_atuacao', models.CharField(max_length=30)),
            ],
        ),
    ]
