# Generated by Django 5.2.6 on 2026-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='tipo_deficiencia',
            field=models.CharField(choices=[('tea', 'Transtorno do Espectro Autista (TEA)'), ('baixa_visao', 'Baixa Visão'), ('cegueira', 'Cegueira'), ('surdez', 'Surdez'), ('surdocegueira', 'Surdocegueira'), ('deficiencia_fisica', 'Deficiência Física'), ('deficiencia_intelectual', 'Deficiência Intelectual'), ('tdah', 'TDAH'), ('dislexia', 'Dislexia'), ('outro', 'Outro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='educador',
            name='area_atuacao',
            field=models.CharField(choices=[('pedagogia', 'Pedagogia'), ('psicologia', 'Psicologia'), ('fisioterapia', 'Fisioterapia'), ('fonoaudiologia', 'Fonoaudiologia'), ('terapia_ocupacional', 'Terapia Ocupacional'), ('assistente_social', 'Assistente Social'), ('outro', 'Outro')], max_length=100),
        ),
    ]
