# Generated by Django 5.2.6 on 2026-05-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='tipo_deficiencia',
            field=models.CharField(blank=True, choices=[('tea', 'Transtorno do Espectro Autista (TEA)'), ('baixa_visao', 'Baixa Visão'), ('cegueira', 'Cegueira'), ('surdez', 'Surdez'), ('surdocegueira', 'Surdocegueira'), ('deficiencia_fisica', 'Deficiência Física'), ('deficiencia_intelectual', 'Deficiência Intelectual'), ('tdah', 'TDAH'), ('dislexia', 'Dislexia'), ('outro', 'Outro')], error_messages={'required': 'Por favor, selecione o tipo de deficiência para que a IA possa personalizar seu atendimento.'}, max_length=100, null=True),
        ),
    ]
